// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3qQ5M0YD1rD1jRWg4QNqRhNurHtJtIM',
    appId: '1:1098119765462:web:e68c2dd35b13ebd34c5877',
    messagingSenderId: '1098119765462',
    projectId: 'madoka-c72c0',
    authDomain: 'madoka-c72c0.firebaseapp.com',
    databaseURL: 'https://madoka-c72c0.firebaseio.com',
    storageBucket: 'madoka-c72c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWg2busDdwGjUYhnRZwdbFtTWxSVb8r7s',
    appId: '1:1098119765462:android:77fd1bc5194d16f94c5877',
    messagingSenderId: '1098119765462',
    projectId: 'madoka-c72c0',
    databaseURL: 'https://madoka-c72c0.firebaseio.com',
    storageBucket: 'madoka-c72c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCio3ULze9xyhbDAN2M51EymwI7yvf9a6Y',
    appId: '1:1098119765462:ios:2b1c49e652acab3f4c5877',
    messagingSenderId: '1098119765462',
    projectId: 'madoka-c72c0',
    databaseURL: 'https://madoka-c72c0.firebaseio.com',
    storageBucket: 'madoka-c72c0.appspot.com',
    iosClientId:
        '1098119765462-tnools5j4lr4599hbkbp7bv5pjdr0gla.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCio3ULze9xyhbDAN2M51EymwI7yvf9a6Y',
    appId: '1:1098119765462:ios:2b1c49e652acab3f4c5877',
    messagingSenderId: '1098119765462',
    projectId: 'madoka-c72c0',
    databaseURL: 'https://madoka-c72c0.firebaseio.com',
    storageBucket: 'madoka-c72c0.appspot.com',
    iosClientId:
        '1098119765462-tnools5j4lr4599hbkbp7bv5pjdr0gla.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionary',
  );
}
